export interface User {
  id: string,
  name: string,
  lastName: string,
  date: string,
  gender: string,
  address: string,
  city: string,
  country: string,
  zipCode: string,
  state: string,
  imageUrl: string,
  desc: string,
  jobTitle: string,
  company: string,
  email: string,
  phone: string,
  vehicle: string,
  imageProfile: string,
  relTransaction: number
}
